services:
    php:
        container_name: php_container
        build:
            context: ./docker
            dockerfile: Dockerfile
        image: simulator/php
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/php.ini:/usr/local/etc/php/php.ini
        networks:
            - application
        restart: unless-stopped
    nginx:
        image: nginx:latest
        container_name: nginx_container
        networks:
            - application
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        links:
            - php
        restart: unless-stopped
    node:
        image: node:18-alpine
        container_name: node_container
        ports:
            - "5173:5173"
        volumes:
            - ./:/usr/src/app
        working_dir: /usr/src/app
        tty: true
        networks:
            - application
networks:
    application:
        driver: bridge
